apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workload
generatorOptions:
  disableNameSuffixHash: true
resources:
  - helm-source.yaml
  - nginx-release.yaml
configMapGenerator:
  - name: nginx-values-cm
    files:
      - values.yaml=nginx-values.yaml
