replicaCount: 6
nodeSelector:
  dedicated: pasx-secure
tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "pasx-secure"
  effect: "NoSchedule"
image:
  repository: bitnami/nginx
  tag: 1.27.3